site_name: 涂林百科
site_url: https://wiki.tulin.me
theme:
  name: material
  palette:
    scheme: slate
    primary: black
    accent: black
  font:
    text: Noto Serif SC
    code: Noto Sans Mono
  language: zh
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.instant
    - navigation.instant.progress
    - search.suggest
    - navigation.footer
  icon:
    repo: fontawesome/brands/github


extra:
  homepage: https://tulin.me
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/talentedbug
    - icon: fontawesome/brands/creative-commons-zero
      link: https://creativecommons.org/public-domain/cc0
    - icon: fontawesome/solid/envelope
      link: mailto:talentedbug@tulin.me

plugins:
  - search
  - offline

copyright: 使用 CC0 授权，允许您自由使用。

repo_url: https://github.com/talentedbug/tulinarchive

markdown_extensions:
  - footnotes
